# Generated by Django 3.0.5 on 2020-04-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(default=None, max_length=20)),
                ('password', models.CharField(default=None, max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('police_office', models.CharField(max_length=20)),
                ('center_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=200)),
                ('region_1depth_name', models.CharField(max_length=50)),
                ('region_2depth_name', models.CharField(max_length=50)),
                ('region_3depth_name', models.CharField(max_length=50)),
                ('road_name', models.CharField(max_length=50)),
                ('zone_no', models.CharField(max_length=20)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Center')),
            ],
        ),
    ]
