# Generated by Django 3.0.5 on 2020-04-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='center_id',
            new_name='login_id',
        ),
    ]
