# Generated by Django 3.0.5 on 2020-04-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building_name',
        ),
    ]
