# Generated by Django 3.0.5 on 2020-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostposting',
            name='p1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostposting',
            name='p2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
