# Generated by Django 3.0.5 on 2020-04-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostaddress',
            old_name='lostposting',
            new_name='posting',
        ),
    ]
