# Generated by Django 3.0.5 on 2020-04-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20200427_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostthumbnail',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='lost.LostImage'),
        ),
    ]
