# Generated by Django 3.0.5 on 2020-04-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_lostthumbnail_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostaddress',
            name='region_1depth_name',
        ),
        migrations.RemoveField(
            model_name='lostaddress',
            name='region_2depth_name',
        ),
        migrations.RemoveField(
            model_name='lostaddress',
            name='region_3depth_name',
        ),
        migrations.RemoveField(
            model_name='lostaddress',
            name='road_name',
        ),
        migrations.RemoveField(
            model_name='lostaddress',
            name='zone_no',
        ),
    ]
