# Generated by Django 3.0.5 on 2020-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0005_auto_20200427_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostposting',
            name='x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostposting',
            name='y',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostposting',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostposting',
            name='lostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lostposting',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
