# Generated by Django 3.0.5 on 2020-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0006_auto_20200427_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostposting',
            name='status',
            field=models.BooleanField(blank=True),
        ),
    ]
