# Generated by Django 3.0.5 on 2020-04-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='foundposting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.Category'),
        ),
        migrations.AlterField(
            model_name='foundposting',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.Color'),
        ),
    ]
