# Generated by Django 3.0.5 on 2020-04-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0003_auto_20200425_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundthumbnail',
            name='posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='found.FoundPosting'),
        ),
    ]
