# Generated by Django 3.0.5 on 2020-04-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0004_auto_20200425_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundposting',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='found.FoundImage'),
        ),
    ]
