# Generated by Django 3.0.5 on 2020-04-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0005_auto_20200426_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundthumbnail',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='found.FoundPosting'),
        ),
    ]
