# Generated by Django 3.0.5 on 2020-04-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0006_auto_20200426_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundthumbnail',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
