# Generated by Django 3.0.5 on 2020-04-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0008_remove_foundposting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundthumbnail',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_path', to='found.FoundPosting'),
        ),
    ]
